---

- name: Install build dependencies
  apt: >
    name={{item}}
    state=present
    update_cache=yes
    cache_valid_time=60
    install_recommends=no
  with_items:
    - build-essential
    - make
    - debhelper
    - git
    - unzip
    - wget
    - curl
